version: '3'
services:

  db:
    image: postgres:latest
    healthcheck:
      test: "exit 0"
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tlnKhan9
      POSTGRES_DB: music

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - .:/go/src/api
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: tlnKhan9
      DB_NAME: music
      DB_PORT: 5432
    links:
      - db
    depends_on:
      - db

volumes:
  db_data:
